---
galaxy_info:
  author: Cloud Codger
  description: Proxmox Guest Machine Remover
  license: GPL-2.0-or-later
  min_ansible_version: '2.10'

  galaxy_tags:
    - cluster
    - hypervisor
    - proxmox
    - pve
    - virtualization

dependencies: []
